### ISSUE TITLE
Removing a member from a group

### ISSUE THREAD

**Issue by SinazoThungo** [witseie-elen4010/2021-001-project-def#110]
- [x]  #113 Remove member button
- [x] #113 Form for reason 
- [ ]  #109 Notify members
- [ ] #74 Start the voting process
- [ ] Remove user or not from the database
