### ISSUE TITLE
Search for users using registration details

### ISSUE THREAD

**Issue by JAllsop** [witseie-elen4010/2021-001-project-def#21]
_As a user I would like to be able to search for other users by their username or email_  

### Tasks  
- [x] #22  for displaying list of users
- [x] #23  for retrieving list of users
- [x] #24  to enable voting of adding a member

### Estimation  
4 Days
